version: '3'

services:
  db:
    image: mysql:5.7
    container_name: plantfeedweb_mysql
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: oauthfarming
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      timeout: 20s
      retries: 10

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: plantfeedweb_backend
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn plantfeed.wsgi:application -b 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  data:
